ALTER TABLE rentals ADD COLUMN returned_at TIMESTAMPTZ;

UPDATE rentals
SET returned_at = updated_at AT TIME ZONE 'Asia/Seoul'
WHERE status = 'RETURNED';

CREATE TABLE reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_id INTEGER NOT NULL REFERENCES rentals(id),
    reviewer_id INTEGER NOT NULL REFERENCES users(id),
    reviewee_id INTEGER NOT NULL REFERENCES users(id),
    rating INTEGER NOT NULL,
    content VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_review_rental_reviewer UNIQUE (rental_id, reviewer_id),
    CONSTRAINT ck_review_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_distinct_users CHECK (reviewer_id <> reviewee_id)
);

CREATE INDEX idx_review_reviewee_created
    ON reviews(reviewee_id, created_at DESC);
CREATE INDEX idx_review_rental ON reviews(rental_id);
