CREATE TABLE push_delivery_tickets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id VARCHAR(100) NOT NULL UNIQUE,
    device_token_id INTEGER NOT NULL REFERENCES user_device_tokens(id),
    status VARCHAR(20) NOT NULL,
    error_code VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    checked_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_push_ticket_status_created
    ON push_delivery_tickets(status, created_at);
